import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    form: {
        width: '87%',
        height: '90%',
        position: 'absolute',
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        borderRadius: 40,
        justifyContent: 'center',
        paddingHorizontal: 25
    },
    imageBackground: {
        width: '100%',
        height: '100%',
        opacity: 0.6
    },
    textRegister: {
        fontSize: 25,
        color: 'white',
        fontWeight: 'bold',
        alignSelf: 'center'
    },
    imageUser: {
        width: 120,
        height: 120,
        alignSelf: 'center'
    },
    imageLogo: {
        width: 150,
        alignSelf: 'center',
        marginBottom: 15
    },
    headerContainer: {
        backgroundColor: '#2196F3',
        paddingTop: 8,
        paddingBottom: 8,
        paddingHorizontal: 24,
        elevation: 8,
        shadowColor: '#2196F3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    headerContent: {
        alignItems: 'center',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
    },
    iconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
        // elevation: 4,
        // shadowColor: '#000000',
        // shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        // shadowRadius: 4,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#FFFFFF',
        marginBottom: 4,
        letterSpacing: 0.5,
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        fontWeight: '500',
    },
    contentContainer: {
        flex: 1,
        paddingTop: 16,
    },
    listContainer: {
        paddingHorizontal: 16,
        paddingBottom: 100,
        flexGrow: 1,
    },
    emptyContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
        paddingVertical: 64,
    },
    emptyIconContainer: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 24,
        elevation: 4,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
    },
    emptyTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: '#424242',
        textAlign: 'center',
        marginBottom: 12,
    },
    emptySubtitle: {
        fontSize: 16,
        color: '#757575',
        textAlign: 'center',
        lineHeight: 24,
        maxWidth: 280,
        marginBottom: 32,
    },
    emptyAddButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#2196F3',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 24,
        gap: 8,
        elevation: 4,
        shadowColor: '#2196F3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    emptyAddButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    bottomSpacer: {
        height: 48,
        backgroundColor: '#000000',
        position: 'absolute',
        bottom: 0,
        width: '100%',
    },
    // Estilos do botão flutuante
    fabButton: {
        position: 'absolute',
        bottom: 110,
        right: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#2196F3',
        alignItems: 'center',
        justifyContent: 'center',
        elevation: 8,
        shadowColor: '#2196F3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    // Estilos do modal
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        maxHeight: '90%',
        paddingBottom: 32,
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingVertical: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
    },
    modalTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    modalIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#2196F3',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    modalTitleTextContainer: {
        flex: 1,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#212121',
        marginBottom: 2,
    },
    modalSubtitle: {
        fontSize: 14,
        color: '#757575',
    },
    modalCloseButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
    },
    formContainer: {
        paddingHorizontal: 24,
        paddingTop: 24,
    },
    inputContainer: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#424242',
        marginBottom: 8,
    },
    vehicleTypeContainer: {
        flexDirection: 'row',
        gap: 12,
    },
    vehicleTypeButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E0E0E0',
        backgroundColor: '#FFFFFF',
        gap: 8,
    },
    vehicleTypeButtonActive: {
        backgroundColor: '#2196F3',
        borderColor: '#2196F3',
    },
    vehicleTypeText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    vehicleTypeTextActive: {
        color: '#FFFFFF',
    },
    textInput: {
        borderWidth: 2,
        borderColor: '#E0E0E0',
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 16,
        backgroundColor: '#FFFFFF',
        color: '#212121',
    },
    validationText: {
        fontSize: 12,
        color: '#FF9800',
        marginTop: 4,
        marginLeft: 4,
    },
    colorContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 8,
    },
    colorButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#E0E0E0',
        backgroundColor: '#FFFFFF',
        gap: 8,
        minWidth: 90,
    },
    colorButtonActive: {
        backgroundColor: '#E3F2FD',
        borderColor: '#2196F3',
    },
    colorPreview: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    colorText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#666',
    },
    colorTextActive: {
        color: '#2196F3',
        fontWeight: '600',
    },
    infoContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 16,
        backgroundColor: '#E3F2FD',
        borderRadius: 12,
        marginTop: 8,
        gap: 12,
    },
    infoText: {
        flex: 1,
        fontSize: 14,
        color: '#1976D2',
        lineHeight: 20,
    },
    modalButtonsContainer: {
        flexDirection: 'row',
        paddingHorizontal: 24,
        paddingTop: 24,
        gap: 12,
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E0E0E0',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#666',
    },
    submitButton: {
        flex: 2,
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: '#2196F3',
        alignItems: 'center',
        justifyContent: 'center',
    },
    submitButtonDisabled: {
        backgroundColor: '#BDBDBD',
    },
    submitButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    // Estilos da barra de pesquisa
    searchContainer: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E0E0E0',
        elevation: 2,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#212121',
        paddingVertical: 4,
    },
    clearButton: {
        padding: 4,
        marginLeft: 8,
    },
    searchResultText: {
        fontSize: 12,
        color: '#666',
        marginTop: 8,
        textAlign: 'center',
        fontStyle: 'italic',
    },
    // Estilos para "nenhum resultado"
    noResultsContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
        paddingVertical: 64,
    },
    noResultsTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#424242',
        textAlign: 'center',
        marginTop: 16,
        marginBottom: 8,
    },
    noResultsSubtitle: {
        fontSize: 14,
        color: '#757575',
        textAlign: 'center',
        lineHeight: 20,
        maxWidth: 280,
    },
    // Estilos da paginação
    paginationContainer: {
        backgroundColor: '#FFFFFF',
        paddingTop: 12,
        paddingHorizontal: 16,
        paddingVertical: 60,
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
        elevation: 4,
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    paginationInfo: {
        alignItems: 'center',
        marginBottom: 12,
    },
    paginationText: {
        fontSize: 12,
        color: '#666',
        fontWeight: '500',
    },
    paginationControls: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    paginationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#F5F5F5',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        gap: 6,
        minWidth: 80,
        justifyContent: 'center',
    },
    paginationButtonDisabled: {
        backgroundColor: '#F9F9F9',
        borderColor: '#F0F0F0',
    },
    paginationButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2196F3',
    },
    paginationButtonTextDisabled: {
        color: '#BDBDBD',
    },
    pageNumbers: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    pageNumberButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E0E0E0',
    },
    pageNumberButtonActive: {
        backgroundColor: '#2196F3',
        borderColor: '#2196F3',
    },
    pageNumberText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    pageNumberTextActive: {
        color: '#FFFFFF',
    },
    pageEllipsis: {
        fontSize: 14,
        color: '#BDBDBD',
        fontWeight: '600',
        paddingHorizontal: 4,
    },
});

export default styles;